# workflows/publish-pg_search.yml
#
# Publish pg_search
# Build and publish the pg_search extension as .deb and .rpm to GitHub Releases.

name: Publish pg_search

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "The version to set for the pg_search release. This publishes the latest commit of the chosen branch and uploads it to the pre-existing GitHub Release of the provided version."
        required: true
        default: ""

concurrency:
  group: publish-pg_search-${{ github.head_ref || github.ref }}

# Used by actions/attest-build-provenance to sign the builds
permissions:
  id-token: write
  attestations: write

jobs:
  publish-pg_search:
    name: Publish pg_search for PostgreSQL ${{ matrix.pg_version }} on ${{ matrix.image }} ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    container:
      image: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu 22.04
          - runner: blacksmith-2vcpu-ubuntu-2204
            image: ubuntu:22.04
            pg_version: 14
            arch: amd64

          # Ubuntu 24.04
          - runner: blacksmith-2vcpu-ubuntu-2404
            image: ubuntu:24.04
            pg_version: 14
            arch: amd64
            # Ubuntu 22.04
          - runner: blacksmith-2vcpu-ubuntu-2204
            image: ubuntu:22.04
            pg_version: 14
            arch: amd64

          # Ubuntu 24.04
          - runner: blacksmith-2vcpu-ubuntu-2404
            image: ubuntu:24.04
            pg_version: 14
            arch: amd64
            # Ubuntu 22.04
          - runner: blacksmith-2vcpu-ubuntu-2204
            image: ubuntu:22.04
            pg_version: 14
            arch: amd64

          # Ubuntu 24.04
          - runner: blacksmith-2vcpu-ubuntu-2404
            image: ubuntu:24.04
            pg_version: 14
            arch: amd64
            # Ubuntu 22.04
          - runner: blacksmith-2vcpu-ubuntu-2204
            image: ubuntu:22.04
            pg_version: 14
            arch: amd64

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Install Debian Dependencies
        if: ${{ matrix.image == 'debian:11-slim' || matrix.image == 'debian:12-slim' || matrix.image == 'ubuntu:22.04' || matrix.image == 'ubuntu:24.04' }}
        run: DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y sudo wget curl gnupg lsb-release pkg-config libssl-dev jq

      - name: Update Package Index
        run: sudo apt-get update

      - name: Install Required Packages
        run: |
          sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg

      - name: Add Docker's Official GPG Key
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

      - name: Set Up Docker Repository
        run: |
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      - name: Install Docker Engine
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Verify Docker Installation
        run: docker --version

      - name: cat /etc/docker/daemon.json
        run: cat /etc/docker/daemon.json

      - name: docker pull ubuntu
        run: docker pull ubuntu

      - name: download pytorch iamge
        run: docker pull pytorch/pytorch
